import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";

function MyApp({ Component, pageProps }: AppProps) {
  const [indexBorder, setIndexBorder] = useState<string>("4px solid #19dae6");
  const [multiBorder, setMultiBorder] = useState<string>("none");

  let setIndex = () => {
    setIndexBorder("4px solid #19dae6");
    setMultiBorder("none");
  };

  let setMulti = () => {
    setMultiBorder("4px solid #19dae6");
    setIndexBorder("none");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.footer}>
        <nav>
          <ul>
            <li>
              <Link href="/">
                <a id="single-player" onClick={setIndex}>
                  Single Player
                </a>
              </Link>
            </li>
            <li>
              <Link href="/multiplayer">
                <a id="multi-player" onClick={setMulti}>
                  Multiplayer
                </a>
              </Link>
            </li>
          </ul>
        </nav>
        <style jsx>{`
          header {
            color: #19dae6;
            font-size: medium;
            font-weight: bold;
          }
          ul {
            display: flex;
            justify-content: center;
            margin-right: 2em;
          }
          li {
            list-style-type: none;
            margin: 0 0.5em;
          }
          #single-player {
            border: ${indexBorder};
            padding: 0.5em;
            border-radius: 4px;
          }
          #multi-player {
            border: ${multiBorder};
            padding: 0.5em;
            border-radius: 4px;
          }
        `}</style>
      </header>
      <div>
        <Component {...pageProps} />
      </div>
      <footer className={styles.footer}>
        By James Jamison &copy; 2021
        <style jsx>{`
          footer {
            color: #19dae6;
          }
        `}</style>
      </footer>
    </>
  );
}
export default MyApp;
