import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Board from "./Components/Board";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Tic-Tac-Toe</h1>
        <Board />
      </main>

      <footer className={styles.footer}>By James Jamison &copy; 2021</footer>
      <style jsx>{`
        h1 {
          color: #19dae6;
          margin: .5em;
        }

        body {
          background: white;
          color: black;
        }

        footer {
          color: #19dae6;
        }

        @media only screen and (max-width: 300px) {
          h1 {
              font-size: 1.5em;
          }
      }
      `}</style>
    </div>
  );
}
